language: php

services:
  - mysql

env:
  global:
    - SS_DATABASE_CLASS=MySQLDatabase
    - SS_DATABASE_USERNAME=root
    - SS_DATABASE_CHOOSE_NAME=1

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env:
       - PHPCS_TEST=1

before_script:
  - composer update

script:
  - vendor/bin/phpunit
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs tests src; fi
